build: use dev version of @agoric/zone
using @agoric/zone@0.2.2 resulted in...

TypeError#3: zone.watchPromise is not a function

upgrading the zone package addressed that but introduced other errors
such as:

Type 'Zone' is not assignable to type 'ExoZone'.

So I did...

$ update-dependencies.js agoric agoric-upgrade-17